import about from './about';
import blog from './blog';
import contacts from './contacts';
import header from './header';
import modal from './modal';
import price from './price';
import promo from './promo';
import services from './services';
import teamSlider from './team';
import worksTab from './works';
window.addEventListener('DOMContentLoaded', ()=>{
    header();
    promo();
    about();
    services();
    worksTab();
    price();
    teamSlider();
    blog();
    contacts();
    modal();
});